package.json

Relevant issues:
https://github.com/e2b-dev/e2b/issues/35#issuecomment-1531591780

Fixate the Supabase CLI version in npm scripts

---

LICENSE
api-service/playground/package-lock.json
api-service/playground/package.json
api-service/playground/swagger.json

Related issues:
https://github.com/e2b-dev/e2b/issues/37

Change license

---

supabase/functions/new_user/index.ts
tsconfig.json

Edge function to create a new contact in Loops.so after the new contact is created in the `users` table.

Supabase - New user function

---

.github/workflows/supabase.yml
supabase/config.toml

Added a GitHub action deployment for Supabase Edge function

Supabase deploy functions

---

api-service/Makefile
api-service/agent/smol_agent.py
api-service/playground/src/sessions/session.ts
api-service/session/session.py
package.json
utils/smolTemplates.ts

Simple prompts to try / use for inspiration

Templates messages

---

apps/docs/src/components/Navigation.tsx

https://github.com/e2b-dev/e2b/assets/697301/37a34eb5-e566-4a03-a18b-9c9e3595c643

fix(docs): Fix sidebar highlighting

---

packages/js-sdk/rollup.config.js
packages/js-sdk/src/index.ts
packages/js-sdk/src/session/index.ts
packages/js-sdk/src/session/process.ts
packages/js-sdk/src/session/sessionConnection.ts
packages/js-sdk/src/session/terminal.ts

This will also allow us to have almost 1:1 tests.

Finish basic parity for JS SDK

---

packages/js-sdk/package.json
packages/js-sdk/src/session/sessionConnection.ts
packages/js-sdk/test/filesystem.test.mjs
packages/js-sdk/test/process.test.mjs
packages/js-sdk/test/session.test.mjs
packages/js-sdk/vitest.config.ts

**Beware**: Cherry-picked commits from other open PR's
https://github.com/e2b-dev/e2b/assets/697301/eff5c9d5-9555-4d68-a80c-a663fe2ab50a

chore(js-sdk): JS SDK tests

---

.changeset/plenty-knives-confess.md
package-lock.json
packages/js-sdk/package.json
packages/js-sdk/rollup.config.js
packages/js-sdk/src/session/error.ts
packages/js-sdk/src/session/sessionConnection.ts
packages/python-sdk/e2b/session/main.py
packages/python-sdk/e2b/session/session_connection.py

- Added API key requirement to JS SDK
- Fixed types for the required API key in Python SDK
- Remove unused optional parameter when starting session
- Removed mangling and compression in JS SDK for better DX

Start requiring API key for starting environment sessions

---

apps/docs/src/components/Code.tsx
apps/docs/src/utils/consts.ts

feat(docs): Convey TS friendliness

---

.changeset/poor-ravens-fly.md
packages/python-sdk/e2b/session/websocket_client.py

Not the nicest solution, but waiting for this issue, which doesn't seem to be solved soon
https://github.com/python-websockets/websockets/issues/1395

Decrease websocket reconnect period

---

apps/docs/package-lock.json
apps/docs/package.json
apps/docs/src/app/api/cli/page.tsx
apps/docs/src/utils/useUser.tsx
packages/cli/package.json
packages/cli/src/commands/auth.ts
packages/cli/src/commands/env/index.ts
packages/cli/src/commands/index.ts
packages/cli/src/config/index.ts
packages/cli/src/index.ts

https://github.com/e2b-dev/e2b/assets/697301/9adc4192-cc6d-42dd-bc84-caafd973699b

feat(docs, cli): CLI auth

---

apps/docs/src/components/Code.tsx
apps/docs/src/utils/useUser.tsx

feat(docs): Start sessions/playground asap, so they are warm to run the code snippets

---

apps/docs/src/components/Auth.tsx
apps/docs/src/components/MobileNavigation.tsx
apps/docs/src/components/Navigation.tsx

fix(docs): Fix menu auth on mobile

---

apps/docs/package.json
pnpm-lock.yaml

Reported to Tailwind https://github.com/tailwindlabs/tailwindcss-typography/pull/301

chore(docs): Fix code margins

---

apps/docs/src/components/Code.tsx

chore(docs): Internal snippets comparison

---

.changeset/silent-mangos-trade.md
packages/js-sdk/src/index.ts

fix(js-sdk): Export CodeRuntime enum

---

.changeset/lazy-penguins-wonder.md
packages/js-sdk/src/session/index.ts

chore(js-sdk): Fix TypeScript types

---

.changeset/real-poems-matter.md
.changeset/silly-hounds-jog.md
packages/js-sdk/src/sandbox/index.ts
packages/js-sdk/src/sandbox/process.ts
packages/python-sdk/e2b/api/__init__.py
packages/python-sdk/e2b/sandbox/main.py
packages/python-sdk/e2b/sandbox/process.py

Improve on_exit handler type so it can accept functions ignoring the exit code argument without type errors.

Improve handler typing

---

.changeset/happy-ligers-join.md
apps/docs/src/app/cli/commands/page.mdx
apps/docs/src/app/sandbox/templates/start-cmd/page.mdx
apps/docs/src/components/Navigation/routes.tsx
packages/js-sdk/src/sandbox/index.ts
packages/python-sdk/e2b/sandbox/main.py

Add start cmd logging to the SDK

---

.changeset/pretty-trains-smell.md
packages/js-sdk/src/sandbox/sandboxConnection.ts
packages/python-sdk/e2b/sandbox/main.py

Fixes https://github.com/e2b-dev/E2B/issues/265

Fix Python code output buffering

---

apps/docs/src/app/guide/custom-sandbox/page.mdx

The custom sandbox guide was using old E2B cli commands

Fix e2b CLI commands

---

.changeset/gold-hotels-breathe.md
.github/workflows/release_candidates.yml
packages/cli/package.json
packages/cli/src/commands/template/build.ts

Fix few issues with cross platform compatibility

Template build command improvements

---

.changeset/loud-donuts-tan.md
apps/docs/src/app/cli/commands/page.mdx
packages/cli/src/commands/sandbox/spawn.ts
packages/cli/src/commands/template/build.ts
packages/cli/src/commands/template/delete.ts
packages/cli/src/config/index.ts
packages/cli/src/options.ts

Add option to specify a config file, this allows to have multiple templates (e.g. prod and staging) based in the same folder.

CLI - add config option

---

.changeset/shiny-houses-fry.md
packages/python-sdk/e2b/sandbox/sandbox_rpc.py

Fix data race condition in Python SDK dictionary

---

apps/docs/package.json
apps/docs/src/app/api/status/route.ts
pnpm-lock.yaml

Add an API endpoint for the E2B status page

Add endpoint for status page

---

apps/web/package.json
apps/web/src/utils/usePostHog.tsx
pnpm-lock.yaml

- Update PostHog JS SDK to the latest version
- Fix the `api_host` field when initializing the PostHog SDK

Update PostHog package and fix the api_host

---

.changeset/purple-garlics-repeat.md
.gitignore
apps/web/src/app/(auth)/auth/layout.tsx
apps/web/src/app/(docs)/docs/cli/commands/page.mdx
apps/web/src/components/Dashboard/Team.tsx
apps/web/src/components/Layout.tsx
apps/web/src/utils/useUser.tsx
packages/cli/src/api.ts
packages/cli/src/commands/auth/configure.ts
packages/cli/src/commands/auth/index.ts
packages/cli/src/commands/auth/info.ts
packages/cli/src/commands/auth/login.ts
packages/cli/src/commands/sandbox/list.ts
packages/cli/src/commands/template/build.ts
packages/cli/src/commands/template/delete.ts
packages/cli/src/commands/template/list.ts
packages/cli/src/config/index.ts
packages/cli/src/options.ts
packages/cli/src/user.ts
packages/cli/src/utils/format.ts
packages/js-sdk/src/api/schema.gen.ts
packages/js-sdk/src/sandbox/index.ts
spec/openapi.yml

- Allows users to configure team in CLI
- Allows specify team for following commands: `list`, `kill`, `delete`

Add multiple team handling

---

apps/web/src/app/(docs)/docs/quickstart/migrating-from-v0/page.mdx

1. Using the remote pattern, users don't need to add anything locally.
2. I usually recommend `--interactive` for new users to review each diff.

feat: update grit guide

---

apps/web/src/components/Layout.tsx
apps/web/src/components/Navigation/index.tsx

Put scrollbar on on the inner side of the sidebar in docs

---

apps/web/src/components/Dashboard/Personal.tsx

Remove old text

---

apps/web/src/app/stream/sandbox/[sandboxId]/page.tsx

Center text

---

apps/web/src/app/(dashboard)/dashboard/page.tsx
apps/web/src/components/Dashboard/Keys.tsx
apps/web/src/components/Dashboard/Sandboxes.tsx

Changelog:
Notes:
- You probably can't try right now, because the backend changes have not been rolled out yet

Updated api key management in dashboard

---

Makefile
packages/connect-python/Makefile

Add command for building dependencies for generating python envd client.

Add command for building dependencies for generating python envd client

---

apps/web/prebuild.js
apps/web/src/components/SdkVersionSelect.tsx
apps/web/src/styles/tailwind.css

Improve SDK ref styling

---

apps/web/src/app/hostnames.ts
apps/web/src/middleware.ts
apps/web/src/utils/replaceUrls.ts

This PR fixes what #493 messed up

Revert root route traffic to the new landing page

---

apps/web/src/app/(docs)/docs/filesystem/page.mdx

Corrects the text in docs regarding the free disks space

Correct free disk space text

---

.changeset/khaki-owls-refuse.md
packages/cli/package.json
packages/cli/src/commands/template/list.ts
packages/js-sdk/src/api/schema.gen.ts
spec/openapi.yml

- Added createdBy, createdAt columns
- Hidden 'buildCount', 'lastSpawnedAt', 'spawnCount', 'updatedAt' columns
- Sync API spec and ts schema to latest

Changed `template ls` command to sync with latest API changes

---

apps/web/src/app/(docs)/docs/page.mdx
apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
apps/web/src/components/Concepts.tsx
apps/web/src/components/Navigation/NavigationLink.tsx
apps/web/src/components/Navigation/routes.tsx
apps/web/src/components/Tag.tsx

This PR adds docs about Sandbox's persistence

Add docs about persistence

---

apps/web/src/components/Dashboard/Personal.tsx

this pr fixes the `href` attribute of the `Reset Password` button in the dashboard

Fix dashboard "Reset Password" href

---

apps/web/src/app/(docs)/docs/troubleshooting/sdks/workers-edge-runtime/page.mdx
apps/web/src/components/Navigation/NavigationLink.tsx
apps/web/src/components/Navigation/routes.tsx

Adds a troubleshooting guide for issues regarding the JS SDK on Vercel Edge Runtime, Cloudflare Workers

Added workers-edge-runtime troubleshooting guide

---

apps/web/src/app/(docs)/docs/quickstart/connect-llms/page.mdx

Added code snippets to documentation for using Groq with E2B.

Add groq to docs

---

apps/web/src/components/Navigation/routes.tsx

show metrics route in the docs sidebar now that the metrics feature is released

Show metrics in sidebar

---

apps/web/src/app/(docs)/docs/code-interpreting/supported-languages/bash/page.mdx
apps/web/src/app/(docs)/docs/code-interpreting/supported-languages/java/page.mdx
apps/web/src/app/(docs)/docs/code-interpreting/supported-languages/javascript/page.mdx
apps/web/src/app/(docs)/docs/code-interpreting/supported-languages/page.mdx
apps/web/src/app/(docs)/docs/code-interpreting/supported-languages/r/page.mdx

This PR fixes incorrect code snippets and wrong link

Fix incorrect code snippets and docs links

---

apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx

Fix broken link in docs

---

packages/js-sdk/tests/sandbox/closed_port.test.ts
packages/js-sdk/tests/sandbox/host.test.ts
packages/python-sdk/tests/async/sandbox_async/test_host.py
packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
packages/python-sdk/tests/sync/sandbox_sync/test_host.py
packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py

Also changed the ports, so if you run locally there's no port collision

Fix flaky tests - Increase the timeout for pinging the server

---

apps/web/src/app/(docs)/docs/code-interpreting/analyze-data-with-ai/page.mdx
apps/web/src/app/(docs)/docs/sandbox/internet-access/page.mdx

doc: fix type of file `apps/web/src/app/(docs)/docs/code-interpreting/analyze-data-with-ai/page.mdx`
doc: fix typo of file `apps/web/src/app/(docs)/docs/sandbox/internet-access/page.mdx`

doc: fix typo

---

.changeset/olive-geese-look.md

Related to changes in https://github.com/e2b-dev/E2B/pull/636

Cli changeset for version release

---

apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx

Update the python beta SDK version to latest

Update Python beta SDK version

---

supabase/functions/new_user/index.ts

In order to populate our crm (hubspot) with new user sign-up data, we need to send the data received by our edge function to the hubspot api.
The hubspot api call got tested via postman and works successfully.
The new environment variable is already added to our supabase production projects edge function secrets.

Add new_user hubspot contact creation

---

supabase/functions/new_user/index.ts

This pr forwards the is_fragments_user metadata field to our hubspot integration in new_user edge function

Forward user metadata is_fragments_user to hubspot

---

packages/js-sdk/tests/sandbox/closed_port.test.ts
packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py

The response from backend for port is actual integer

Fix test for closed ports

---

packages/js-sdk/tests/api/list.test.ts

The test was moved to integration tests directly in infra repo

Remove order check from SDK.

---

apps/web/src/app/(docs)/docs/cli/page.mdx
apps/web/src/app/(docs)/docs/sandbox/connect/page.mdx
apps/web/src/app/(docs)/docs/sandbox/installing-beta-sdks/page.mdx
apps/web/src/app/(docs)/docs/sandbox/list/page.mdx
apps/web/src/app/(docs)/docs/sandbox/metadata/page.mdx
apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx
apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
apps/web/src/components/Navigation/routes.tsx

- Added notices in "Connect to running sandbox", "Sandbox metadata" docs.
- Updated "List sandboxes", "Sandbox persistence" docs.
- Renamed route "List running sandboxes"  > "List sandboxes".

Updated docs on Sandbox.list v2

---

packages/cli/package.json
packages/js-sdk/package.json
packages/python-sdk/poetry.lock
pnpm-lock.yaml

Fixes:
https://github.com/e2b-dev/E2B/security/dependabot/163
https://github.com/e2b-dev/E2B/security/dependabot/157
https://github.com/e2b-dev/E2B/security/dependabot/156
https://github.com/e2b-dev/E2B/security/dependabot/148
https://github.com/e2b-dev/E2B/security/dependabot/147

Security patches

---

apps/web/src/app/(docs)/docs/sandbox/environment-variables/page.mdx

- Minor change that fixes incorrect parameter in the docs

docs: env > envs in Environment variable doc

---

supabase/functions/new_user/index.ts

This pr removes the HubSpot contact creation from our `/new_user` edge function.

Remove HubSpot contact creation

---

apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx

Reverts e2b-dev/E2B#717
Metrics aren't public yet

Revert "Update metrics docs beta note to be public "

---

apps/web/src/mdx/search.mjs

This pr removes the legacy docs from the search indexing script, which will also remove them from the actual search in runtime. Also it adds logging to increase build observability.

Remove: legacy docs from search

---

packages/js-sdk/tests/runtimes/browser/run.test.tsx
packages/js-sdk/vitest.workspace.mts

Fix browser tests domain when used not against production

Fix browser tests domain

---

apps/web/src/app/(docs)/docs/sandbox/installing-beta-sdks/page.mdx

- updated beta versions of code interpreter, core and desktop SDKs in the install guide

Updated SDK beta versions in docs

---

.changeset/tough-dots-live.md
packages/cli/LICENSE
packages/js-sdk/LICENSE
packages/python-sdk/LICENSE

- Added licenses source text to the SDKs, CLI

Added license sources to SDKs

---

.changeset/curvy-badgers-compete.md
packages/python-sdk/e2b/exceptions.py

- this is a follow-up to #777, fixing the timeout exception format option

Changes timeout exception format

---

apps/web/next.config.mjs

- Adds a redirect from the old path to the updated doc

Redirect /docs/getting-help > /docs/support

---

.changeset/shy-knives-shake.md
packages/cli/src/commands/template/build.ts

Print all logs also on build success

Print all logs also on build success

---

apps/web/src/app/(docs)/docs/sandbox/rate-limits/page.mdx
apps/web/src/components/Navigation/routes.tsx

Adds page with details about rate limits.

Add rate limits page

---

.changeset/grumpy-insects-rescue.md
packages/cli/src/api.ts
packages/cli/src/commands/template/delete.ts
packages/cli/src/commands/template/list.ts
packages/cli/src/commands/template/publish.ts
packages/cli/src/user.ts
packages/cli/src/utils/format.ts
packages/js-sdk/src/api/index.ts

Fix the check and remove deprecated fields

Fix API key check in JS SDK & remove deprecated fields

---

apps/web/src/app/(docs)/docs/migration/v2/page.mdx
apps/web/src/app/(docs)/docs/sandbox/list/page.mdx
apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
apps/web/src/app/(docs)/docs/sdk-reference/python-sdk/v2.0.0/sandbox_async/page.mdx
apps/web/src/app/(docs)/docs/sdk-reference/python-sdk/v2.0.0/sandbox_sync/page.mdx
apps/web/src/components/Navigation/routes.tsx
apps/web/src/images/diagram.svg
packages/python-sdk/e2b/sandbox_sync/paginator.py

Adds migration guide for SDK v2
Adds mentions about auto pause
https://e2b-web-git-migration-guide-v2.e2b-preview.dev/docs/migration/v2

Add migration guide to docs

---

.changeset/dirty-chicken-allow.md
packages/js-sdk/src/template/index.ts
packages/js-sdk/src/template/types.ts
packages/python-sdk/e2b/template/main.py

Add ready command for JS and Python (accidentally omitted before).

Add ready command for JS and Python
