package.json

Found it from here: https://github.com/python-poetry/poetry/issues/689#issuecomment-755452534
The `--no-root` flag stops poetry from trying to install the package. https://python-poetry.org/docs/cli/#:~:text=If%20you%20want%20to%20skip%20this%20installation%2C%20use%20the%20%2D%2Dno%2Droot%20option

Fix install:all; poetry error fixed by adding --no-root flag.

---

supabase/functions/new_user/index.ts

I am open for other suggestions. The reason for choosing this name:
- It's descriptive
- Will be always true

Supabase - Changed group name for a new user

---

apps/dashboard/next.config.js
apps/docs/next.config.mjs

This is an improvement for local development and vercel previews - otherwise you would have to always add `/dashboard` or `/docs` to the url.

Add redirectd from `/` pages for docs and dashboard

---

apps/docs/src/app/playgrounds/overview/page.mdx
apps/docs/src/components/Code.tsx
apps/docs/src/components/mdx.tsx
apps/docs/src/mdx/remark.mjs

`````
/* BEFORE */
<CodeGroup>
```python {{ language: 'python', snippet: 'python/basics/init.py' }}
```
```js {{ language: 'js', snippet: 'js/basics/init.js' }}
```
</CodeGroup>
/* AFTER */
<CodeGroupAutoload path="basics/init" />
`````

CodeGroupAutoload

---

.changeset/rare-moons-dream.md
packages/js-sdk/src/session/sessionConnection.ts

Mostly to test automatic deployment

chore(js-sdk): Log session init/termination by default

---

.changeset/blue-shirts-sneeze.md
packages/python-sdk/e2b/templates/data_analysis.py

The goal of this PR is to have the same API for downloading artifacts for both JS and Python SDK:
Python
```python
artifact_bytes = artifact.download()
```
JS
```js
const artifact_buffer = await artifact.download()
```
Python SDK had `artifact.read()`  and `artifact.download()`. The `read` method returned `bytes` and `download` wrote to a local file. I got rid of the original `download` method (leaving writing to a file to the user) and renamed the original `read` to `download`.

remove artifact.read() and leave only download()

---

.changeset/fifty-cats-divide.md
packages/python-sdk/e2b/templates/data_analysis.py

It was `apt-get {package}` instead of `apt-get install {package}`

Fix `install_system_packages` method in the Python SDK

---

.changeset/five-lemons-join.md
packages/python-sdk/e2b/api/__init__.py

In python 3.9 and below you can't do something like str | None in the type definition of a function's arguments. However, this can be fixed by using __future__. 
Python stores the annotations as strings and doesn't try to evaluate them. This allows you to write type hints using Python 3.10's syntax in a Python 3.9 environment. When the code is actually run, the annotations aren't evaluated, so there's no issue with the interpreter not understanding the | operator for union types.

Use __future__ annotation to fix backwards compatibility for union

---

.changeset/stale-eels-care.md
packages/cli/src/commands/build.ts
packages/cli/src/config/index.ts

This start command is provided during template build, executed on FC start and snapshotted with the sandbox template. After starting sandbox users will have this command already running there.

Add start cmd option for the build in the CLI

---

.changeset/blue-buckets-pump.md
packages/js-sdk/src/index.ts
packages/js-sdk/src/sandbox/sandboxConnection.ts
packages/python-sdk/e2b/__init__.py
packages/python-sdk/e2b/sandbox/__init__.py
packages/python-sdk/e2b/sandbox/sandbox_connection.py

The sanbdox ID returned from SDKs `list` method was missing the client id part user had to manually create the whole valid ID.
Now the sandbox ID field returned by the list method has the whole ID and the client ID is removed from the object.

Fix sandbox ID returned from SDKs `list` methods

---

.changeset/sweet-masks-suffer.md
packages/cli/src/commands/sandbox/kill.ts

CLI `e2b sandbox kill` command didn't work with sandboxIDs provided by the `e2b sandbox list`. This PR fixes that.

Fix sandbox kill command

---

apps/docs/src/app/sandbox/templates/premade/page.mdx

`sandbox.close` would be a no-op without parentheses to invoke the function.

Add missing parentheses in `sandbox.close()` call

---

.changeset/tasty-items-cross.md
.changeset/warm-bears-suffer.md
packages/cli/src/api.ts
packages/cli/src/commands/sandbox/list.ts
packages/cli/src/commands/template/build.ts
packages/cli/src/commands/template/delete.ts
packages/cli/src/commands/template/list.ts
packages/js-sdk/src/api/index.ts
packages/js-sdk/src/constants.ts
packages/js-sdk/src/index.ts
packages/js-sdk/src/sandbox/sandboxConnection.ts
packages/python-sdk/e2b/__init__.py
packages/python-sdk/e2b/api/__init__.py
packages/python-sdk/e2b/constants.py
packages/python-sdk/e2b/sandbox/main.py
packages/python-sdk/e2b/sandbox/sandbox_connection.py

Add `domain` parameter to SDK create, list, and kill methods to allow specifying sandbox API domain with a different way than just the `E2B_DOMAIN` env var.

Add domain parameter to SDK

---

apps/reverse-proxy/vercel.json

Adds a redirect rule for the `https://e2b.dev/careers` route to redirect to `https://e2bdev.notion.site/Careers-at-E2B-2163f176991f43f69b0984bf2a142920?pvs=74`

Add redirect to the careers Notion page

---

apps/docs/src/code/python/basics/metadata.py

Sandbox.create() is deprecated in favor of Sandbox(), updating docs example.

Update metadata.py to not use deprecated Sandbox.create() method

---

.changeset/smart-seals-hope.md
packages/js-sdk/src/sandbox/index.ts
packages/js-sdk/src/sandbox/sandboxConnection.ts

This prevents to accidentally use `new Sandbox()`, which doesn't initialize `Sandbox` class correctly

Enforce calling create method in JS SDK

---

.changeset/small-oranges-roll.md
packages/python-sdk/e2b/sandbox/websocket_client.py

This should prevent from sending a lot of request to our infrastructure when the sandbox is already closed

Add max retries to websocket reconnect in Python SDK

---

.changeset/strange-readers-scream.md
apps/docs/src/app/cli/commands/page.mdx
apps/docs/src/app/sandbox/templates/template-file/page.mdx
packages/cli/src/commands/template/build.ts

This feature allows users to pass arguments used during the template build.
E.g.:
```
e2b template build --build-arg="HELLO=WORLD" --build-arg="MULTIPLE=True"
```

CLI add build args

---

README.md
apps/web/src/utils/consts.ts

Corrected documentation links in the README.md for "Documentation" and utils/const.ts.
Review Required for `pnpm run dev:docs`: The dev:docs script in package.json currently links to apps/docs and cannot be run locally unless it is changed to apps/web. 
Didn't want to change the package.json right away, thought i'd let you know about this first instead.

Fix links from apps/doc to apps/web

---

apps/web/src/app/(docs)/docs/code-interpreter/template/page.mdx
apps/web/src/app/(docs)/docs/guide/beta-migration/page.mdx
apps/web/src/components/Navigation/routes.tsx
pnpm-lock.yaml

Add a page with a migration guide that shows how to use the new beta Core SDK, Code Interpreter SDK, and async version of the Python SDKs.

Add beta SDK migration guide

---

packages/js-sdk/src/sandbox/index.ts
packages/python-sdk/e2b/sandbox/main.py

If you want to download a file from sandbox you need to use the SDK right now.
The download URL method we are adding lets you get the link to a file in sandbox that you can then use to download the file, for example on the frontend, with a direct link.

Add `download_url`/`downloadUrl` method to sandbox

---

apps/web/src/app/(docs)/docs/guide/beta-migration/page.mdx

Docs don't explain what language the exception names are for. Update the docs to reflect that.

Update doc to explain the exception name based on the language used

---

.prettierrc
packages/cli/package.json
packages/cli/scripts/generate_api_ref.sh
packages/cli/src/index.ts
packages/cli/src/utils/commands2md.ts
pnpm-lock.yaml

-  upgraded the `-cmd2json` root option to `-cmd2md`
-  it calls a `commands2md` utils custom function that converts command objects to Markdown documentation
- this function writes all root command documentation files into the `api_ref/` 
- boyscouting: added root `.prettierrc`
```bash
cd packages/cli
./scripts/generate_api_ref.sh 
ls ./api_ref
```
This could eventually be used directly as .mdx in the docs nextjs app, it would look like this with current styling and TOC:

Auto-generate API reference markdown files for the CLI

---

apps/web/src/app/(docs)/docs/hello-world/js/page.mdx
apps/web/src/app/(docs)/docs/hello-world/py/page.mdx

The current Getting Started examples are broken because 1) they don't specify the Anthropic SDK version and 2) they use exports from a deprecated beta version.
The example code has now been migrated in the cookbook (https://github.com/e2b-dev/e2b-cookbook/commit/d28460156cf07e23c114581dc6dfafb71493418d) so I'm copying it into the documentation here to fix the examples.
The Anthropic SDK version has also been notes to avoid our examples suddenly breaking in the future.

Fix Getting Started Examples

---

Makefile
apps/web/src/code/python/basics/fs_watch.py
packages/js-sdk/src/sandbox/filesystem/index.ts
packages/js-sdk/src/sandbox/filesystem/watchHandle.ts
packages/js-sdk/tests/sandbox/files/watch.test.ts
packages/python-sdk/e2b/envd/filesystem/filesystem_connect.py
packages/python-sdk/e2b/envd/filesystem/filesystem_pb2.py
packages/python-sdk/e2b/envd/filesystem/filesystem_pb2.pyi
packages/python-sdk/e2b/envd/process/process_connect.py
packages/python-sdk/e2b/envd/process/process_pb2.py
packages/python-sdk/e2b/envd/process/process_pb2.pyi
packages/python-sdk/e2b/sandbox/process/process_handle.py
packages/python-sdk/e2b/sandbox_async/filesystem/filesystem.py
packages/python-sdk/e2b/sandbox_async/filesystem/watch_handle.py
packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
packages/python-sdk/e2b/sandbox_sync/filesystem/watch_handle.py
packages/python-sdk/e2b/sandbox_sync/main.py
packages/python-sdk/e2b/sandbox_sync/process/process.py
packages/python-sdk/tests/async/sandbox_async/files/test_watch.py
packages/python-sdk/tests/sync/sandbox_sync/files/test_watch.py
spec/envd/filesystem/filesystem.proto

Current solution didn't work well with in sync Python. If you're unsure whether a file has been created, you might end up waiting for a timeout to exit the loop. 
New implementation uses polling, you can ask for events whenever you want and it will request envd to send all events (or only new ones). This should make it much better for users with sync Python SDK
Example of a problematic usage before and after:
```python
sbx = Sandbox()
watcher = sbx.files.watch("/home/user")
sbx.files.make_dir("test")
for event in watcher:
print(event)
break
watcher.close()
```
```python
sbx = Sandbox()
watcher = sbx.files.watch("/home/user")
sbx.files.make_dir("test")
events = watcher.get_new_events()
watcher.stop()
for event in events:
print(event)
```
Even worse case was if you don't know if anything …

Improve file watcher in Python Sync SDK

---

.changeset/itchy-clouds-know.md
packages/js-sdk/src/api/index.ts
packages/js-sdk/src/errors.ts
packages/python-sdk/e2b/api/__init__.py
packages/python-sdk/e2b/exceptions.py

There's only general exception raised right now. I've added specific exception when the request is denied because of throttling

Add rate limit error

---

.changeset/tall-parrots-wink.md
packages/python-sdk/poetry.lock
packages/python-sdk/pyproject.toml

I cannot run `pipenv run e2b-code-interpreter` as I get a dependency conflict with an existing package which requires `attr >= 24.0`
This change will allow `e2b-code-interpreter` to be used in more places

Make python dependencies more lenient

---

apps/web/src/components/Dashboard/Team.tsx

pending https://github.com/e2b-dev/billing/pull/18

Add user by e-mail

---

apps/web/src/app/(docs)/docs/filesystem/download/page.mdx
apps/web/src/app/(docs)/docs/quickstart/upload-download-files/page.mdx

The Python examples were using read that returned string, but we were using it as bytes in the examples.
Users already opened two issues about this that we had to solve until they mentioned it is wrong in the docs.

Fix docs examples for Python SDK `read` method

---

packages/cli/src/commands/sandbox/list.ts
packages/cli/src/commands/template/list.ts
packages/cli/src/utils/format.ts

Remove table borders in CLI

---

packages/js-sdk/tests/api/list.test.ts

This PR is meant to test the changes found in `APIStore.GetSandboxes` https://github.com/e2b-dev/infra/pull/211

Assert that the returned sandbox info objects are sorted by start time

---

apps/web/src/components/Dashboard/Team.tsx

- Adds "added by" and "added at" columns to the table
- Changes to API /teams/:id/users headers
Blocked by https://github.com/e2b-dev/billing/pull/25

Adds "added by" and "added at" columns to the table, changes to API header

---

apps/web/src/app/(dashboard)/dashboard/layout.tsx
apps/web/src/app/(dashboard)/dashboard/page.tsx
apps/web/src/components/Dashboard/AccountSelector.tsx
apps/web/src/components/Dashboard/Billing.tsx
apps/web/src/components/Dashboard/Developer.tsx
apps/web/src/components/Dashboard/Keys.tsx
apps/web/src/components/Dashboard/Personal.tsx
apps/web/src/components/Dashboard/Sandboxes.tsx
apps/web/src/components/Dashboard/Team.tsx
apps/web/src/components/Dashboard/Templates.tsx
apps/web/src/components/Dashboard/Usage.tsx
apps/web/src/components/Footer.tsx
apps/web/src/components/Pricing/SwitchToProButton.tsx

- Click on team dropdown > Developer
- Setting alternative API URL
- Setting alternative Billing URL
- Resetting the above to defaults (provided by env variable)

Added developer panel

---

packages/cli/src/commands/template/index.ts
packages/cli/src/commands/template/publish.ts

Adds publish/unpublish commands to the CLI to allow changing the visibility of templates. Publishing a template makes it visible to other teams using E2B, while setting it private (default) only makes it visible within your own team.
example usage:
``` 
e2b template publish <template>
```
```
e2b template unpublish <template>
```

Added publish/unpublish commands to the CLI

---

apps/web/src/components/AuthForm.tsx

this pr fixes the following in a local development environment:
- supabase auth redirect after oauth sign in
- forgot password flow
this is accomplished by using `document.location.origin`, to always use the url on which the auth flow was started. this makes sense if different developers use different ports for their app development and when authenticating on vercel preview urls.

Redirect to localhost instead of e2b.dev after sign in with oauth in dev environment

---

packages/python-sdk/e2b/sandbox_async/commands/command_handle.py
packages/python-sdk/e2b/sandbox_sync/commands/command_handle.py
packages/python-sdk/tests/async/sandbox_async/commands/test_run.py
packages/python-sdk/tests/sync/sandbox_sync/commands/test_run.py

The `sbx.commands.run` method can generate a `stdout` with badly encoded `UTF-8` bytes, which can cause this kind of errors: 
```py
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 8191: unexpected end of data
```
see more here: https://linear.app/e2b/issue/E2B-1291/unicodedecodeerror-in-python-sdk-when-using-curl-command
To address this we update the `decode` error handler to replace with the unicode replacement char. 
```sh
poetry run pytest -s -n 4 -k "tests/sync/sandbox_sync/commands/test_run"
```

Make stdout and stderr handle decode errors gracefully 

---

apps/web/src/components/Dashboard/Templates.tsx
apps/web/src/components/ui/toast.tsx

Fixes: Visible > Public
Toast opacity to 100:

Fixes the label in template section and toast opacity

---

apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx

Docs persistence

---

apps/web/src/components/Dashboard/Developer.tsx

This PR addresses a bug when a user passes a custom API URL like `https://api.e2b-cluster.dev` and we incorrectly print that the user should set their `E2B_DOMAIN` to `api.e2b-cluster.dev` while the correct one would be `E2B_DOMAIN=e2b-cluster.dev`.

Correctly parse the API URL in dashboard

---

apps/web/src/app/(dashboard)/dashboard/page.tsx
apps/web/src/app/(dashboard)/dashboard/utils.ts
apps/web/src/components/Dashboard/Billing.tsx
apps/web/src/components/Dashboard/Developer.tsx
apps/web/src/components/Dashboard/Keys.tsx
apps/web/src/components/Dashboard/Personal.tsx
apps/web/src/components/Dashboard/Sandboxes.tsx
apps/web/src/components/Dashboard/Team.tsx
apps/web/src/components/Dashboard/Templates.tsx
apps/web/src/components/Dashboard/Usage.tsx
apps/web/src/components/Pricing/SwitchToProButton.tsx

Billing service runs on `billing.` subdomain, so you can pass only 1 url now

Use billing subdomain to simplify dashboard for custom domains 

---

packages/js-sdk/tests/integration/template/e2b.Dockerfile
packages/js-sdk/tests/integration/template/e2b.toml

Create a template dedicated to running integration tests. For now we're interested in having a full-blown nextjs app running in the sandboxes to check their behavior under various conditions. 
```sh
cd packages/js-sdk/tests/integration/template/
E2B_DOMAIN=e2b-staging.com e2b template build
```

Integration test template build

---

apps/web/src/components/Header.tsx
apps/web/src/components/Layout.tsx
apps/web/src/components/MobileBurgerMenu.tsx
apps/web/src/components/Search.tsx
apps/web/src/mdx/search.mjs
apps/web/types.d.ts

this pr adds the following:
1. non "api-reference" or "sdk-reference" documentation files are indexed on build time and made full text searchable via `flexsearch`
2. `<Search />` component is added to the docs navigation on desktop & mobile accordingly
3. preview snippets are visualised for each `SearchResult`

Add search capabilities to documentation

---

apps/web/src/middleware.ts

This PR makes sure that the `https://e2b.dev/cookbook` route correctly displays the content of the cookbook page that's part of our landing page on our Webflow.

Add `/cookbook` page 

---

apps/web/src/middleware.ts
apps/web/src/utils/replaceUrls.ts

This PR updates the middleware rules so it fetches the new changelog page hosted on Webflow when user goes to `https://e2b.dev/changelog`.

Display the new changelog page

---

apps/web/src/components/Search.tsx
apps/web/src/mdx/search.mjs
apps/web/types.d.ts

This pr adds a `badge` attribute to documentation indices, which can represent a string literal for certain badge types defined in the `Result` type. 
Possible types at the time of writing: `"Legacy" | undefined`
On each documentation query, we sort all search results containing a badge value of `Legacy` at last and render a badge containing the string value in each search result item.

Show badge for legacy documentation search results

---

apps/web/package.json
apps/web/src/components/LegacyBanner.tsx
apps/web/src/components/Search.tsx
apps/web/src/components/mdx.tsx
pnpm-lock.yaml

This pr adds:
1. posthog event captures for two new events: "docs search" & "docs search result click"
2. notice banner on legacy documentation pages
3. search results scrollability in dialog

Capture documentation search analytics & improve legacy docs handling

---

apps/web/src/components/LegacyBanner.tsx
apps/web/src/components/Search.tsx

This pr adds the following:
1. prevents unnecessary analytics event captures when user erases query & user navigates through results with arrow keys
2. changes docs page legacy banner prose (v.1.0 -> v1.0)

Fix duplicate search analytics event captures

---

apps/web/src/app/(docs)/docs/sandbox/environment-variables/page.mdx

This PR clarifies language about default env var

Update docs page about env vars

---

apps/web/src/app/(docs)/docs/sandbox/list/page.mdx

Update docs to make it clear how sandbox filtering works with multiple key-value metadata pairs.

Clarify how filtering works with multiple key-value pairs

---

apps/web/src/utils/useUser.tsx

The column was moved from `Team` to `UserTeam`, because one team can be the default for a specific user, but not to all of them. This is addressing the logic in dashboard

Fix default user for the user

---

packages/js-sdk/src/envd/api.ts
packages/js-sdk/src/sandbox/index.ts
packages/js-sdk/src/sandbox/sandboxApi.ts
packages/js-sdk/tests/sandbox/create.test.ts
packages/python-sdk/e2b/api/__init__.py
packages/python-sdk/e2b/sandbox_async/main.py
packages/python-sdk/e2b/sandbox_async/sandbox_api.py
packages/python-sdk/e2b/sandbox_sync/main.py
packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
packages/python-sdk/tests/async/sandbox_async/test_create.py
packages/python-sdk/tests/sync/sandbox_sync/test_create.py

Add envd version when creating sandbox to allow for check if features are available

Add envd version to SDKs

---

apps/web/src/app/(dashboard)/dashboard/page.tsx
apps/web/src/components/Dashboard/AccountSelector.tsx
apps/web/src/components/Dashboard/BillingAlerts.tsx
apps/web/src/components/Dashboard/Usage.tsx
apps/web/src/components/ui/alert-dialog.tsx
apps/web/src/components/ui/skeleton.tsx
apps/web/src/utils/useUser.tsx
package.json

Adds the ability for teams to set up a budget limit and a budget alert.
The following two sections were added under the dashboards `Usage` tab:
1. Section for setting a `Billing Limit` in `$ (USD)` which blocks the team when reached & sends notifications along the way to the teams primary email address
2. Section for settings a `Billing Alert` in `$ (USD)` which sends a notification to the teams primary email address when reached

Implement budget alerts & limit

---

apps/web/src/components/Dashboard/BillingAlerts.tsx

Clarify wording for usage limits & alerts

Update wording for usage limits and alerts

---

apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx
apps/web/src/components/Navigation/routes.tsx

This documents the new SDK method implemented [here](https://github.com/e2b-dev/E2B/pull/543)

Add sandbox metrics docs page

---

apps/web/src/app/(docs)/docs/page.mdx

Fix typo in docs

---

apps/web/src/components/Navigation/routes.tsx

Hide metrics route in the docs sidebar until the feature is fully released

Hide metrics in sidebar

---

.changeset/sweet-pots-pull.md
packages/cli/src/commands/template/build.ts

If the build and push takes more than 10 minutes the connection gets automatically closed by load balancer and the request fails with UND_ERR_SOCKET error. In this case we just need to retry the request.

Fix Socket closed build error

---

apps/web/next.config.mjs

This pr adds `assetPrefix` property to the `next.config ` for production builds. This makes sure that absolute urls instead of relative ones are used on asset urls in the html markup, which makes it possible to proxy this app from our upcoming new next app.

Add assetPrefix to next config

---

apps/web/next.config.mjs

This pr fixes the following issue for [#569](https://github.com/e2b-dev/E2B/pull/569):
The production vercel environment did not refer assets to the correct production domain through VERCEL_URL. Hence a custom environment variable was added to the production environment to account for that.

Fix: assetPrefix refers to correct domains for production & preview environments

---

apps/web/src/middleware.ts

This PR updates the middleware to direct the `/blog` traffic to the new Webflow landing page

Redirect `/blog` to the new blog website

---

packages/cli/src/commands/sandbox/metrics.ts

this addresses theses issues pointed out by @jakubno :
```
No need to return timestamp if it's already in square brackets
[2025-02-04 19:28:08.627Z]  { cpuCount: 2, cpuUsedPct: 3.23, memTotalMiB: 987, memUsedMiB: 55, timestamp: '2025-02-04T19:28:08.62741452Z' }
And if you do json format, there level field
{"timestamp":"2025-02-04T19:28:08.62741452Z","level":"","cpuCount":2,"cpuUsedPct":3.23,"memTotalMiB":987,"memUsedMiB":55}
```

Remove level field and deduplicate timestamp field 

---

.changeset/twelve-planets-attend.md
packages/js-sdk/src/api/metadata.ts

Variable `process` isn't present in browser

Fix usage in browser

---

apps/web/src/app/layout.tsx

This PR adds necessary Google Tag Manager identification tags to our next.js app. Primary focus for the GTM here lies on `/dashboard `& `/docs`

E2B-1546: add google tag manager capibilites for /docs

---

package.json

This PR updates the packageManager field in package.json to the latest 9.x version release (9.15.5).
Currently the specified version 8.x is invalid with the configuration limit for engine:
```
"engines": {
"pnpm": ">=9.0.0 <10"
} 
```

Update package manager to the latest 9.x version (9.15.5)

---

apps/web/src/app/sitemap.ts
apps/web/src/middleware.ts
package.json

This pr extends the middleware to rewrite `/blog/category/:path*` to our Webflow Landing Page. Additionally, `sitemap.xml` got improved & fixed by caching it statically on build time.

Rewrite /category in middleware

---

apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx

This PR removes a requirement for reaching to get access to persistence as persistence is now in public beta.

Update persistence docs

---

.changeset/warm-grapes-applaud.md
packages/cli/src/commands/template/build.ts

This PR improves CLI messaging when building sandbox templates. Now, the used Docker commands are explicitly logged to the user like this:
```
Building docker image with the following command:
docker build . \ # <--- This log is new
-f e2b.Dockerfile \
--pull --platform linux/amd64 \
-t docker.e2b.dev/e2b/custom-envs/vqwjjtzwfi59d1cwww1k:ec8a819a-9666-45df-997b-e181b9fe4224 
[+] Building 0.7s (5/5) FINISHED                                                                              docker:desktop-linux
=> [internal] load build definition from e2b.Dockerfile                                                                      0.0s
=> => transferring dockerfile: 149B                                                                                          0.0s
=> [internal] load metadata …
```

Explicitly mention Docker commands when building template

---

.changeset/stale-owls-own.md
packages/cli/src/index.ts
packages/cli/tsup.config.js

Load update notifier dynamically
We needed update the package because of vulnerabilities
If we don't load it asynchronously there's following error.
```
packages/cli generate-ref: /home/runner/work/E2B/E2B/packages/cli/dist/index.js:55406
packages/cli generate-ref: var updateNotifier = __toESM(require("update-notifier"));
packages/cli generate-ref:                              ^
packages/cli generate-ref: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/E2B/E2B/node_modules/.pnpm/update-notifier@6.0.2/node_modules/update-notifier/index.js from /home/runner/work/E2B/E2B/packages/cli/dist/index.js not supported.
packages/cli generate-ref: Instead change the require of /home/runner/work/E2B/E2B/node_modules/.pnpm/update-notifier@6.0.2/node
```

Fix CLI build issue

---

apps/web/src/components/LegacyBanner.tsx
apps/web/src/components/Navigation/routes.tsx

This pr improves the legacy banner visibility in legacy documentation pages by utilizing the brand color (dark orange) on border, text and background.

Improve legacy banner visibility in /docs

---

.changeset/sweet-geese-yell.md
DEV.md
packages/cli/src/api.ts

Before the urls in our error messages pointed to a doc page that doesn't exist. This change updates the urls with links that resolve to dashboard
also adds note on how to create changesets

Show resolvable url in error message

---

packages/js-sdk/package.json

Pin typdoc to non-breaking versions in js-sdk which allow non-ESM imports.

Fix SDK reference generation in js-sdk

---

pnpm-lock.yaml

The lockfile does not reflect the pinned versions of typedoc from https://github.com/e2b-dev/E2B/pull/602

Update pnpm lockfile

---

apps/web/src/app/(docs)/docs/quickstart/page.mdx
apps/web/src/app/(docs)/docs/quickstart/upload-download-files/page.mdx

this pr fixes / improves the following issues with the quick start section in our documentation:
1. `/docs/quickstart `-> sign up link was broken
2. `/docs/quickstart/upload-download-files `-> removed `Sandbox.create()` in python code snippets and replaced with `Sandbox()`. added better explanation on the folder locations (relative on own machine, absolute on sandbox)

Fix docs quick start issues

---

packages/js-sdk/src/sandbox/filesystem/index.ts
packages/python-sdk/tests/sync/sandbox_sync/files/test_watch.py

The previous [release workflow]([Release](https://github.com/e2b-dev/E2B/commit/b3fe5e6777357a7d814c7dbe4525a18f3f83288f/checks)) errored after merging this [old PR](https://github.com/e2b-dev/E2B/pull/451), here are the fixes:

Fix release test for multi-file write support  

---

packages/js-sdk/tests/sandbox/files/write.test.ts

Sandbox is closed before the test ends, which resulted in error. The clean up is meant for local testing only

Fix failing write test

---

apps/web/next.config.mjs

on our landing page & documentation we have references to outdated urls. for an upcoming event, redirects should be in place to avoid broken links. the redirects should only be temporary and the broken references should be fixed when resources are available to do so

Add temporary docs redirects 

---

apps/web/src/app/(docs)/docs/code-interpreting/analyze-data-with-ai/page.mdx
apps/web/src/app/(docs)/docs/code-interpreting/create-charts-visualizations/static-charts/page.mdx

the following issues with the code-interpreting documentation have been fixed:
1. https://e2b.dev/docs/code-interpreting/analyze-data-with-ai not working in python
2. https://e2b.dev/docs/code-interpreting/create-charts-visualizations/static-charts unnecessary line of code in python

Fix code interpreting documentation snippets

---

apps/web/src/app/hostnames.ts
apps/web/src/middleware.ts

This PR resolves the Cloudflare IP blocking issue by:
1. Adding www prefix to landing page hostname
2. Properly handling request headers with new Headers object
3. Adding redirect handling to follow redirects
4. Refactoring middleware response handling for proper URL rewriting
These changes prevent Cloudflare from identifying our requests as suspicious automated traffic while maintaining the functionality of our proxy middleware.

Fix Webflow proxying with www-prefixed hostname and proper request handling

---

.changeset/khaki-shirts-switch.md
apps/web/src/app/(docs)/docs/sandbox/page.mdx
packages/js-sdk/src/sandbox/index.ts
packages/js-sdk/src/sandbox/sandboxApi.ts
packages/js-sdk/tests/sandbox/timeout.test.ts
packages/python-sdk/e2b/sandbox/sandbox_api.py
packages/python-sdk/e2b/sandbox_async/main.py
packages/python-sdk/e2b/sandbox_async/sandbox_api.py
packages/python-sdk/e2b/sandbox_sync/main.py
packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
packages/python-sdk/tests/async/sandbox_async/test_timeout.py
packages/python-sdk/tests/sync/sandbox_sync/test_timeout.py

Add getInfo/get_info methods to the SDKs

---

apps/web/src/app/(docs)/docs/sandbox/page.mdx
packages/js-sdk/tests/api/info.test.ts
packages/python-sdk/tests/async/api_async/test_sbx_info.py
packages/python-sdk/tests/sync/api_sync/test_sbx_info.py

getInfo: added tests, updated documentation with example return

---

.github/scripts/is_release_for_package.sh
.github/workflows/release.yml

Inspired by original change in code-interpreter release process https://github.com/e2b-dev/code-interpreter/pull/72

Script for per-package check if release is needed

---

apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx
apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx

Update the python beta SDK version to latest

Update package versions

---

.changeset/tasty-candles-leave.md
packages/cli/src/commands/template/build.ts

- Fixing #650, on Windows commands cannot separate arguments by backslash (\).

Remove backslashes from the docker build command (Windows)

---

.github/workflows/cli_tests.yml
.github/workflows/js_sdk_tests.yml
.github/workflows/publish_packages.yml
.github/workflows/python_sdk_tests.yml
.github/workflows/supabase.yml
.github/workflows/templates.yml

There is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

Update Ubuntu base image to 22.04

---

.github/workflows/publish_packages.yml

To avoid errors like [these](https://github.com/e2b-dev/E2B/actions/runs/14200197836/job/39785152642) where we publish without any sdk ref changes.

Show SDK ref dir only when it exists

---

apps/web/public/.well-known/security.txt

Added file under `/.well-known/security.txt` to match security standards for security or abuse reports.
More details why this is well known address by search engines or security researchers can be found here:
https://www.rfc-editor.org/rfc/rfc9116

Added security.txt under well-known

---

.changeset/serious-rocks-exist.md
packages/js-sdk/src/sandbox/index.ts

Works well in my Cloudflare PoC https://github.com/rychlis/e2b-edge-test/blob/main/src/index.ts
PoC is using these APIs work well:
- `Sandbox.create`
- `sandbox.commands.run` with background ture
I use follow as per @ValentaTomas comment here https://github.com/e2b-dev/E2B/issues/531#issuecomment-2779492867
Few notes:
- I use beta release so I based this PR on beta, can do separate PR to main if needed
- Maybe I can only change this behavior based on detected runtime, but I think it might be safe
- Didn't look into E2B testing suite yet. My PoC only tests APIs I listed, maybe there are other edge runtime issues I didn't uncover yet
Should fix https://github.com/e2b-dev/E2B/issues/531

Fix edge runtime issue - use redirect: follow fetch option

---

.changeset/lemon-maps-sleep.md
packages/js-sdk/src/sandbox/index.ts

backports the changes from beta branch (#669)

(Workers) Patch connect-es fetch transport to always use redirect: follow

---

.changeset/selfish-cars-relax.md
packages/python-sdk/e2b/sandbox/filesystem/filesystem.py

One should now be able to use sb.filesystem.write(WriteEntry[]) in a typesafe way.

Fix minor issue in python filesystem SDK

---

.github/workflows/publish_packages.yml

This was initially performed in [the legacy workflow](https://github.com/e2b-dev/E2B/blob/d27f81c5d3a85e2791258e388eb7ebd5f2e5eaa9/.github/workflows/generate_sdk_ref.yml#L101-L117) but has since been removed, adding it back to have latest [desktop & code-interpreter SDK references](https://e2b.dev/docs/sdk-reference) on our docs

Clone remote desktop & code-interpreter SDK refs into E2B sdk refs folder during publish 

---

.changeset/fifty-points-cross.md
.changeset/serious-rocks-exist.md
packages/cli/package.json
packages/js-sdk/package.json
packages/python-sdk/pyproject.toml

- removes outdated change sets
- bumped packages versions
- CLI version was unchanged because the current version is not on NPM
- Python beta SDK was updated few hours ago?

bump beta versions

---

apps/web/src/app/(docs)/docs/cli/list-sandboxes/page.mdx
apps/web/src/components/Navigation/routes.tsx

- Adds docs on the `e2b sandbox list` command in the current Beta version of the CLI.

Adde CLI beta list command docs

---

.changeset/cuddly-buckets-tie.md
packages/python-sdk/e2b/__init__.py
packages/python-sdk/e2b/api/__init__.py
packages/python-sdk/e2b/connection_config.py
packages/python-sdk/e2b/sandbox_async/main.py
packages/python-sdk/e2b/sandbox_async/sandbox_api.py
packages/python-sdk/e2b/sandbox_sync/main.py
packages/python-sdk/e2b/sandbox_sync/sandbox_api.py

PR that allows you to pass `proxy` (of the type ProxyTypes) when calling methods in the SDK that send requests. Also, if you pass `proxy` when creating a sandbox, all the sandbox requests (called on the Sandbox/AsyncSandbox instance) will automatically use the same proxy.
The PR also contains a small bugfix—adding missing passing of limits and passing these directly instead of through transport to be able to pass the proxy parameter properly.
This change should also be compatible with the code interpreter—it uses the client transport, which uses the passed proxy if there is any.

Add option for proxying SDK requests to API and sandbox

---

.changeset/spotty-eagles-complain.md
packages/cli/src/user.ts

- Respect `E2B_DOMAIN` for `e2b auth login` in CLI
- Keep `E2B_DOCS_BASE` to allow for running dashboard locally or towards potentially different domain

Respect `E2B_DOMAIN` for `e2b auth login` in CLI

---

.changeset/tidy-meals-develop.md
packages/cli/src/commands/sandbox/connect.ts

Allow for short sandbox ID in CLI when using `e2b sandbox connect <sandbox-id>`

Allow for short sandbox id in `e2b sbx connect`

---

packages/js-sdk/src/sandbox/index.ts
packages/js-sdk/tests/api/snapshot.test.ts
packages/python-sdk/e2b/sandbox_async/main.py
packages/python-sdk/e2b/sandbox_sync/main.py
packages/python-sdk/tests/async/api_async/test_sbx_snapshot.py
packages/python-sdk/tests/sync/api_sync/test_sbx_snapshot.py

- Added Sandbox.pause static method in JavaScript, Python BETA SDKs
- Added tests for the above
**Example**
JS
```ts
const sbx = await Sandbox.create()
await Sandbox.pause(sbx.sandboxId) // can be used in a background job for example
await Sandbox.resume(sbx.sandboxId)
```
Python
```py
sbx = Sandbox()
Sandbox.pause(sbx.sandbox_id)
Sandbox.resume(sbx.sandbox_id)
```

Adds ability to pause Sandbox using Sandbox.pause() static class method

---

packages/js-sdk/vitest.workspace.mts

Like in pytest, we should be running all the tests before reporting test results. Currently, vitest finishes after 1 test has failed, this could cause confusion if your new test should be running after the failing one.

Vitest: continue after failing test

---

apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx

The metrics command is not in private beta as it does not require a special cluster.

Update metrics docs beta note to be public 

---

apps/web/src/app/(docs)/docs/quickstart/connect-llms/page.mdx

Adds an example how to use E2B with Hugging Face's serverless inference API to the quickstart guide.

Add hugging face to the quickstart guide

---

.changeset/tasty-lemons-grow.md
packages/cli/src/api.ts

To show the correct error message in our cli, we need to break the switch cases. Currently always the last case will be applied, no matter the input.

Fix authErrorBox switch breaking

---

.changeset/ninety-cobras-tan.md
packages/cli/src/commands/template/build.ts

- Adds `--no-cache` parameter to CLI `template build` command for building templates without cache.

Added --no-cache option for building templates without cache

---

apps/web/src/app/(docs)/docs/sandbox-template/start-cmd/page.mdx

Network is now available when running a start command. Remove the network limitation from the documentation.

Update template start command limits in docs

---

apps/web/src/components/Navigation/NavigationSubgroup.tsx
apps/web/src/components/Navigation/index.tsx

This pr improves the initial navigation sub groups expanded state, by passing in the pathname as a prop instead of hooking it in and determining the state in an effect. This avoid layout shifts when doing initial page renders, while inside a navigation subgroup item

Chore: pass pathname as prop into navigation group to avoid layout shift on initial render

---

apps/web/src/app/layout.tsx
apps/web/src/app/sitemap.ts
apps/web/src/middleware.ts

This pr fixes validating pathnames for SEO metadata tag generation, by checking against already built time cached sitemap instead of doing request time glob resolution. path resolutions in vercels request-time are hard to optimize for & test, since the environment differs quite a bit from what could be tested locally + this should be faster since the fetch & sitemap are cached for the build.

Fix: path validation for metadata tags resolution

---

.changeset/four-numbers-drive.md
apps/web/src/app/(docs)/docs/legacy/sandbox/custom/page.mdx
apps/web/src/app/(docs)/docs/legacy/sandbox/templates/overview/page.mdx
apps/web/src/app/(docs)/docs/sandbox-template/page.mdx
apps/web/src/app/(docs)/docs/sandbox-template/ready-cmd/page.mdx
apps/web/src/app/(docs)/docs/sandbox-template/start-cmd/page.mdx
apps/web/src/components/Navigation/routes.tsx
packages/cli/README.md
packages/cli/package.json
packages/cli/src/commands/template/build.ts
packages/cli/src/config/index.ts
packages/cli/src/utils/errors.ts
packages/js-sdk/package.json
pnpm-lock.yaml

Add option for a template ready check. You can specify `ready_cmd` which will be run until it exits with code 0. Max timeout is 5 minutes. After exit code 0, the template will be marked as ready.
If no ready command is defined, `sleep 20` is assumed when the start command is present, and `sleep 0` when none is defined. It is also possible to define ready command without any start command. This might be helpful if the filesystem contains self-booted services (e.g. using systemd).
```
ready_cmd = "echo 'Starting ready check'; sleep 40; echo 'Template is ready'"
```
This adds possibility to configure the default 20 seconds wait time for a start command.
New documentation can be found at `/docs/sandbox-template/ready-cmd`.

Add option for a template ready check

---

.changeset/many-boats-knock.md
packages/js-sdk/src/sandbox/index.ts
packages/js-sdk/src/sandbox/signature.ts
packages/js-sdk/src/utils.ts
packages/js-sdk/tests/sandbox/files/signing.test.ts
packages/js-sdk/tests/sandbox/secure.test.ts

- Replaces node:crypto with cross-runtime TextEncoder/TextDecoder API
- The uploadUrl/downloadUrl methods are now async

Use TextEncoder for crypto/signed URLs

---

.changeset/twenty-pears-kick.md
packages/js-sdk/src/sandbox/filesystem/index.ts

- removes redundant "timeout" option for watchDir method in the JS SDK (we're using timeoutMs already)

watchDir remove redundant "timeout" option in JS SDK

---

.changeset/mighty-dragons-shake.md
packages/python-sdk/e2b/envd/rpc.py
packages/python-sdk/e2b_connect/client.py

What was happening is the sandbox was timing out, connect client was not parsing the error correctly (while streaming command) and you got a parsing error instead of sandbox timeout exception
- Fixes https://github.com/e2b-dev/desktop/issues/97 > read response content
- Adds handling for http response status code (such as 502) from the server
Example code:
```py
from e2b import Sandbox
import time
def main():
sandbox = Sandbox(
timeout=10,
)
info = sandbox.get_info()
start_time = info.started_at.timestamp()
while True:
elapsed_seconds = time.time() - start_time
sandbox.commands.run("ls -la")
print(f"Run command at {time.time()}, {elapsed_seconds:.2f} seconds elapsed")
if __name__ == "__main__":
main()
```
Before:
```
Run command at 1751560744.80317, 0.77 seconds elapsed
Run command at …
```

Fixes parsing http errors in connect client

---

.changeset/green-roses-know.md
packages/cli/src/commands/sandbox/connect.ts
packages/cli/src/commands/sandbox/list.ts
packages/js-sdk/src/sandbox/sandboxApi.ts
packages/python-sdk/e2b/sandbox/sandbox_api.py
packages/python-sdk/e2b/sandbox_async/sandbox_api.py
packages/python-sdk/e2b/sandbox_sync/sandbox_api.py

- CLI spawn, connect, and logs work with and without the client part provided
- JavaScript and Python SDKs are no longer returning IDs with client part

Client ID part removal from SDKs

---

.changeset/clever-pets-complain.md
packages/cli/src/commands/template/build.ts

This will allow customers who are not using our Docker repository to fall back to their own during template build.

Add image URI mask option for template build to allow custom image repository

---

apps/web/src/app/(docs)/docs/sandbox-template/page.mdx

Add note about Debian based images limitation for the template build. The link leads to Wikipedia: https://en.wikipedia.org/wiki/List_of_Linux_distributions#Debian-based. E2B leads to: https://hub.docker.com/u/e2bdev

Add note about Debian based images limitation

---

.changeset/plenty-foxes-press.md
packages/js-sdk/src/api/metadata.ts
packages/js-sdk/src/connectionConfig.ts
packages/js-sdk/src/sandbox/index.ts
packages/python-sdk/e2b/api/metadata.py
packages/python-sdk/e2b/connection_config.py
packages/python-sdk/e2b_connect/client.py

The bug where extra fields in envd response caused an exception was fixed in #738. As we're also ignoring new fields in envd (implemented in https://github.com/e2b-dev/infra/pull/847). We now have to update the `user-agent` header.

Update `User-Agent` header in SDKs based on the SDK version

---

apps/web/src/components/Navigation/routes.tsx

This pull request updates the title of a navigation route in the `docRoutes` configuration to improve clarity and consistency.
From:
To:

Update documentation title for file and directory metadata

---

apps/web/package.json
apps/web/src/components/Navigation/index.tsx
apps/web/src/components/SdkVersionSelect.tsx
pnpm-lock.yaml

Sorting the versions lexicographically was not ordering by latest correctly, now using `semver` package to sort them:
```ts
> versions = [
'1.9.0',  '1.8.0',
'1.7.0',  '1.6.0',
'1.5.0',  '1.4.0',
'1.3.0',  '1.2.0',
'1.12.0', '1.11.0',
'1.10.0', '1.1.0',
'1.0.0'
]
> versions.sort((a, b) => semver.rcompare(a, b))
[
'1.12.0', '1.11.0',
'1.10.0', '1.9.0',
'1.8.0',  '1.7.0',
'1.6.0',  '1.5.0',
'1.4.0',  '1.3.0',
'1.2.0',  '1.1.0',
'1.0.0'
]
```

Sort SDK version for dropdown using semver package

---

.changeset/wicked-ghosts-tie.md
apps/web/src/app/(docs)/docs/filesystem/download/page.mdx
apps/web/src/app/(docs)/docs/filesystem/upload/page.mdx
packages/js-sdk/src/sandbox/index.ts
packages/js-sdk/tests/sandbox/files/signing.test.ts
packages/js-sdk/tests/sandbox/secure.test.ts
packages/python-sdk/e2b/sandbox/main.py
packages/python-sdk/tests/async/sandbox_async/files/test_secured.py
packages/python-sdk/tests/sync/sandbox_sync/files/test_secured.py

Some users report that JS/Python types lack a `useSignature` attribute, which only works when `secure=true` is set for the sandbox. This change removes the `useSignatrue` parameter and makes all upload/download URL requests signed if `secure` was provided, making sure the function will work for all possible cases.

Secured sandbox auto signature

---

.changeset/strange-hornets-judge.md
packages/python-sdk/e2b/connection_config.py
packages/python-sdk/e2b/sandbox/main.py
packages/python-sdk/e2b/sandbox/sandbox_api.py
packages/python-sdk/e2b/sandbox_async/commands/command.py
packages/python-sdk/e2b/sandbox_async/commands/pty.py
packages/python-sdk/e2b/sandbox_async/filesystem/filesystem.py
packages/python-sdk/e2b/sandbox_async/main.py
packages/python-sdk/e2b/sandbox_async/sandbox_api.py
packages/python-sdk/e2b/sandbox_sync/commands/command.py
packages/python-sdk/e2b/sandbox_sync/commands/pty.py
packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
packages/python-sdk/e2b/sandbox_sync/main.py
packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
packages/python-sdk/tests/sync/sandbox_sync/files/test_secured.py

Several improvements and refactors to the Python SDK's sandbox connection and configuration logic. 
The main focus is on making header management more flexible, improving API parameter handling, and simplifying class structures for better maintainability and usability. 
Also unifies doc strings

Simplify connection config handling in Python SDK

---

.changeset/hungry-cups-warn.md
packages/js-sdk/package.json
packages/js-sdk/src/template/buildApi.ts
packages/js-sdk/src/template/types.ts
packages/js-sdk/src/utils.ts
pnpm-lock.yaml

We bundled `strip-ansi` module but it is ESM-only, it caused a runtime when trying to `require()` ESM-only module from the bundle (on older Node versions).
- Inlined the code from `strip-ansi` into `utils.ts` so it can be correctly bundled.
- Fixes #894

Vendor strip-ansi npm module to avoid ESM-related issues

---

packages/js-sdk/src/envd/api.ts
packages/js-sdk/src/envd/versions.ts
packages/js-sdk/src/sandbox/commands/index.ts
packages/js-sdk/src/sandbox/index.ts
packages/python-sdk/e2b/envd/versions.py
packages/python-sdk/e2b/sandbox/main.py
packages/python-sdk/e2b/sandbox_async/commands/command.py
packages/python-sdk/e2b/sandbox_async/filesystem/filesystem.py
packages/python-sdk/e2b/sandbox_async/main.py
packages/python-sdk/e2b/sandbox_sync/commands/command.py
packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
packages/python-sdk/e2b/sandbox_sync/main.py

The envd is always present, so we can simplify the handling + pass it to filesystem module as a preparation for stdin

Improve envd version handling
